services:
  supervision-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supervision-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_URI}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - FRONTEND_ORIGINS=${FRONTEND_ORIGIN}
      - NODE_ENV=${NODE_ENV}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - lamentaciones-network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"  
      - "15672:15672" 
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lamentaciones-network
  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus-server
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
         - "9090:9090"
      networks:
        - lamentaciones-network
  grafana:
      image: grafana/grafana:latest
      container_name: grafana-dashboard
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin 
      networks:
        - lamentaciones-network
networks:
  lamentaciones-network:
    driver: bridge